### ISSUE TITLE
Don't take XP from player when using the menu

### ISSUE THREAD

**Issue by AfkF24** [BetterGUI-MC/AnvilGUI#17]
Basically what the title says. 1 experience level is taken from players when using the menu, due to "renaming" the item.

**Comment by AfkF24** [comment]
This actually looks like it's a client issue... The xp doesn't actually get removed from the player, it's just the visual.

**Comment by HSGamer** [comment]
There is nothing I can do with this issue. It might be the issue with the [AnvilGUI](https://github.com/WesJD/AnvilGUI) library, so we may wait for them to fix it.
